frame_stack: 4
hidden_dim: 512
lr: 0.0005
min_lr: 0.0001
rollout_length: 512
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.1
value_coef: 0.5
entropy_coef: 0.05
e_decay_end: 3500000
max_grad_norm: 1.0
ppo_epochs: 5
batch_size: 512
window_ma: 50
max_frames: 10000000