frame_stack: 4
hidden_dim: 512
lr: 0.001
min_lr: 0.0001
rollout_length: 1024
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
value_coef: 0.5
entropy_coef: 0.05
e_decay_end: 1000000
max_grad_norm: 2.0
ppo_epochs: 5
batch_size: 256
window_ma: 10
max_frames: 6000000