frame_stack: 4
hidden_dim: 512
lr: 1e-4
rollout_length: 128
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
value_coef: 0.5
entrop_coef: 0.01
max_grad_norm: 0.5
ppo_epochs: 5
batch_size: 256
window_ma: 500 
max_frames: 6000000